### ISSUE TITLE
sweetalert updated version

### ISSUE THREAD

**Issue by shayts** [toverux/ngsweetalert2#24] opened 2017-09-27 07:30 UTC
Is this library wrapping the latest version of SweetAlert?
I have a bug using ngswwtalert2 which was fixed in sweetAlert long time ago:
https://github.com/limonte/sweetalert2/releases/tag/v4.0.0

**Comment by toverux** [comment] 2017-09-27 09:54
It does not embark it direclty, it has it in its dependencies. The current semver version range is `^6.6.0`, which allows the latest version of SweetAlert2 (v6.9.1) to be installed, yes (but I'm surprised you're linking SweetAlert2 4.x since SweetAlert 6.x was already out when this library is born).

Try to run `npm upgrade @toverux/ngsweetalert2`. Not sure about that command, so if that's still not working, just remove and reinstall @toverux/ngsweetalert2. The dependency on SweetAlert2 will be resolved again and the latest version will be installed.

**Comment by shayts** [comment] 2017-09-27 10:44
this is what I have in my package.json file:
@toverux/ngsweetalert2": "^1.2.2"

It seems I got an old version.
tried to run npm upgrade @toverux/ngsweetalert2 but I get the same version.

Any ideas what could be the problem?

**Comment by toverux** [comment] 2017-09-27 11:27
v1.2.2 is the latests NgSweetAlert2 version, that's good.
Try to run `npm remove @toverux/ngsweetalert2`, then `npm install @toverux/ngsweetalert2`.

**Comment by shayts** [comment] 2017-09-27 13:38
tried it but still having the same problem.
It seems like ngsweetalert2 is using an old version of sweetalert.
Is there a way to check which version of sweetalert is being used?

**Comment by limonte** [comment] 2017-09-27 13:53
@toverux as your repo gaining some popularity you will need to learn to detect newbies and, probably, don't spend much time on them :)

@shayts in future, put some effort and some code into your questions.

**Comment by shayts** [comment] 2017-09-27 14:11
@limonte I'm not a newbie and don't think you'r approach is right. helping others (specially newbies) is not a bad thing or a waste of time.
If you don't want to help other that's you're choice but asking other people not to help is definitely wrong.

about putting some effort and code into my question:

import swal, { SweetAlertType } from 'sweetalert2'

swal({
            title: "some title",
            html: '<label>hello</label>',
            showCancelButton: true,
            })
            .then(val => {
                //this function is callec when user click the cancel button
            }, (dismiss) => {
            });

**Comment by limonte** [comment] 2017-09-27 14:46
@shayts this is the example of proper effort OS-software developers expecting from bug-reporters: https://github.com/limonte/sweetalert2/issues/626

3 things are required to get the proper support:

- **Plunkr that reproduces the problem:**
- Expected behavior
- Actual behavior

Copy-pasted code from your project doesn't help a lot to debug.

**Comment by toverux** [comment] 2017-09-28 11:21
@shayts, I've already helped you by identifying the problem's source. Which is not the library itself: it comes from the package manager. I had to repeat myself in my second post and I could repeat me again, but @limonte is right.
GitHub is a place where you can signal bugs, provide help, ask "advanced" questions directly to the mainteners, etc. It's not the new StackOverflow.

I agree that a peer dependency on SweetAlert2 would have avoided this problem at first place, but NgSweetAlert2 does _not_ prevent you to have the latest version.

> Is there a way to check which version of sweetalert is being used?

Why don't you Google that? Yes, open `package-lock.json` if you are using npm 5+ or `yarn.lock` if you are using yarn. This is a list of all the packages installed, directly or indirectly, with their exact resolved version. For example, if I create a directory and just run `npm install @toverux/ngsweetalert2`, I get the latest SweetAlert version, as reported in the `package-lock.json`:

```json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@toverux/ngsweetalert2": {
      "version": "1.2.2",
      "resolved": "https://registry.npmjs.org/@toverux/ngsweetalert2/-/ngsweetalert2-1.2.2.tgz",
      "integrity": "sha1-xINjcB6AgFx9FcoNCYfb4XmaIaM=",
      "requires": {
        "sweetalert2": "6.9.1"
      }
    },
    "sweetalert2": {
      "version": "6.9.1",
      "resolved": "https://registry.npmjs.org/sweetalert2/-/sweetalert2-6.9.1.tgz",
      "integrity": "sha512-VzxO+oq4XgfnGd/wVJsAce/1lfEUyX6zIQZ4bnPaNue1coTFDodsqwLBKGpzYex8/uuZexbc3GenVeZDQguf5g=="
    }
  }
}
```

**Closed by toverux** 2017-09-28 11:21 UTC
