### ISSUE TITLE
Is it possible to use other components inside sweetalert?

### ISSUE THREAD

**Issue by lippomano** [toverux/ngsweetalert2#19] opened 2017-08-16 10:59 UTC
Is it possible to put some third part component inside sweetalert?
I want to show my sweetalert when someone have to change password, Inside this sweetalert I need 3 input fields ( old password, new password and confirm new password)
But the new password field needs to be a something like this:
https://www.primefaces.org/primeng/#/password  or 
https://github.com/rnadler/ng2-password-strength-bar
Is it possible to use different input fields?

**Comment by toverux** [comment] 2017-08-16 11:41
Hi @lippomano,
It's not possible yet, unfortunately. You can set pure HTML, but not an Angular template.
This has been asked in issue #16 and I've already done some research, but that looks hard to implement.

Closing as duplicate of #16. Please subscribe to it in order to receive new about this. For now, I recommend you to use a classic input field and use preConfirm/etc to check the password strength (SweetAlert2 also supports displaying a validation message, so you can already do something nice).

**Closed** 2017-08-16 11:41 UTC
Labels: question
